-[----->+<]>---.  # Prints "E"
+[-->+<]>.      # Prints "n"
-[--->+<]>-.    # Prints "t"
+[----->+<]>.   # Prints "e"
+[-->+<]>.      # Prints "r"
++++++++++.     # Prints " "
-[----->+<]>---.  # Prints "a"
++++++++++.     # Prints " "
-[------->+<]>-.  # Prints "n"
+[-->+<]>.      # Prints "u"
-[->++<]>-.     # Prints "m"
-[--->+<]>----. # Prints "b"
+[----->+<]>.   # Prints "e"
-[--->+<]>-.    # Prints "r"
++++++++++.     # Prints ":"
++++++++++.     # Prints " "
